name: Build-Ghost-APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # ប្ដូរមកប្រើ Action នេះវិញ ព្រោះវា Update ជាង និងមិន Error
        uses: jreleaser/buildozer-action@v1
        with:
          command: yes | buildozer -v android debug
          repository_root: .

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Update ទៅ v4 តាមការណែនាំរបស់ GitHub
        with:
          name: Ghost-DDoS-VIP-Final
          path: bin/*.apk
