name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # ត្រូវតែប្រើ ArtemGr (អក្សរ A និង G ជាអក្សរធំ)
        uses: ArtemGr/buildozer-action@v1.6.1
        with:
          workdir: .
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ghost-DDOS-APK
          path: bin/*.apk
